# docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:3.9.10-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=1qaz2wsx